version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      github-actions:
        patterns:
          - *

  # Keep dependencies for Composer up-to-date
  - package-ecosystem: composer
    directory: /
    schedule:
      interval: monthly
    groups:
      composer:
        patterns:
          - *

  # Enable updates to the dependencies of our Dockerfile
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly
