name: Configlet Sync

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 4 * * # 4th day of each month

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  configlet-sync:
    uses: exercism/github-actions/.github/workflows/configlet-sync.yml@main
    with:
      sync_docs: true
      sync_tests: true
