name: Exercise linting with PHPCS for PSR 12

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: PHPCS Linting - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        php-version: [8.4]
        os: [ubuntu-24.04]

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10

      - uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc
        with:
          php-version: ${{ matrix.php-version }}
          extensions: gmp
          tools: composer

      - name: Install composer packages
        run: composer install --no-scripts

      - name: Lint exercises
        shell: bash
        run: composer lint:check
